In [6]:
import tensorflow_hub as hub

import tensorflow_text as text

In [7]:
preprocessed_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

encoder_url="https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [8]:
bert_preprocess_model = hub.KerasLayer(preprocessed_url)

In [21]:
sample_text=["Every one" , "its a fine day","All is well", "everthing looks good"]


In [23]:
sample_text_preprocessed = bert_preprocess_model(sample_text)

In [24]:
sample_text_preprocessed

{'input_type_ids': <tf.Tensor: shape=(4, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [25]:
sample_text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [26]:
sample_text_preprocessed['input_mask']

<tf.Tensor: shape=(4, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [29]:
bert_model = hub.KerasLayer(encoder_url)
bert_enc_model_pre_prc = bert_model(sample_text_preprocessed)

In [30]:
bert_enc_model_pre_prc

{'pooled_output': <tf.Tensor: shape=(4, 768), dtype=float32, numpy=
 array([[-0.80359674, -0.1829325 ,  0.43246937, ...,  0.30906963,
         -0.58048034,  0.81647986],
        [-0.9530575 , -0.50191176, -0.9102744 , ..., -0.73288316,
         -0.8092662 ,  0.9717138 ],
        [-0.93779045, -0.48707867, -0.8915404 , ..., -0.6830718 ,
         -0.7196919 ,  0.95571566],
        [-0.7808974 , -0.20695128,  0.2798446 , ...,  0.3405512 ,
         -0.5575365 ,  0.8327014 ]], dtype=float32)>,
 'sequence_output': <tf.Tensor: shape=(4, 128, 768), dtype=float32, numpy=
 array([[[-0.24350886,  0.4277286 , -0.21961635, ..., -0.03739277,
           0.16718459, -0.10350697],
         [ 0.19953683,  0.40957856,  0.53397906, ...,  0.16639663,
           0.36847037, -0.06304058],
         [-0.80106497,  0.54117686,  0.19511569, ...,  0.420175  ,
          -0.24643493, -0.8609677 ],
         ...,
         [-0.06938811,  0.28188822,  0.62965584, ...,  0.17838372,
          -0.00838893,  0.06099574],
 

In [31]:
bert_enc_model_pre_prc.keys()

dict_keys(['pooled_output', 'sequence_output', 'default', 'encoder_outputs'])